// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hilandyn2_int_cpp
arma::vec hilandyn2_int_cpp(arma::mat& X, arma::uword nb, arma::uword nc, const arma::uword nt, const arma::uword nr, const arma::uvec ts_ids, const bool cell_weights, const bool rmse_out, const bool len_seg_out, const bool slo_seg_out, const bool bln_mat_out, const bool zsc_mat_out, const bool mag_mat_out, const bool sgn_mat_out, const bool est_mat_out, const arma::uword nout, const arma::uword ts_len_min, const arma::uword gap_len_max, const std::string sd_method, const arma::vec cng_dir, const double noise_zscore, const std::vector<std::string>& wavelet_filters, const arma::sword wavelet_level, const double wavelet_filter_penalty, const double acf_min, double th_min, double th_max, double dBIC_min, double seg_len_min, const arma::uword cpt_max, bool verbose);
RcppExport SEXP _hilandyn2_hilandyn2_int_cpp(SEXP XSEXP, SEXP nbSEXP, SEXP ncSEXP, SEXP ntSEXP, SEXP nrSEXP, SEXP ts_idsSEXP, SEXP cell_weightsSEXP, SEXP rmse_outSEXP, SEXP len_seg_outSEXP, SEXP slo_seg_outSEXP, SEXP bln_mat_outSEXP, SEXP zsc_mat_outSEXP, SEXP mag_mat_outSEXP, SEXP sgn_mat_outSEXP, SEXP est_mat_outSEXP, SEXP noutSEXP, SEXP ts_len_minSEXP, SEXP gap_len_maxSEXP, SEXP sd_methodSEXP, SEXP cng_dirSEXP, SEXP noise_zscoreSEXP, SEXP wavelet_filtersSEXP, SEXP wavelet_levelSEXP, SEXP wavelet_filter_penaltySEXP, SEXP acf_minSEXP, SEXP th_minSEXP, SEXP th_maxSEXP, SEXP dBIC_minSEXP, SEXP seg_len_minSEXP, SEXP cpt_maxSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type ts_ids(ts_idsSEXP);
    Rcpp::traits::input_parameter< const bool >::type cell_weights(cell_weightsSEXP);
    Rcpp::traits::input_parameter< const bool >::type rmse_out(rmse_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type len_seg_out(len_seg_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type slo_seg_out(slo_seg_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type bln_mat_out(bln_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type zsc_mat_out(zsc_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type mag_mat_out(mag_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type sgn_mat_out(sgn_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type est_mat_out(est_mat_outSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type ts_len_min(ts_len_minSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type gap_len_max(gap_len_maxSEXP);
    Rcpp::traits::input_parameter< const std::string >::type sd_method(sd_methodSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type cng_dir(cng_dirSEXP);
    Rcpp::traits::input_parameter< const double >::type noise_zscore(noise_zscoreSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type wavelet_filters(wavelet_filtersSEXP);
    Rcpp::traits::input_parameter< const arma::sword >::type wavelet_level(wavelet_levelSEXP);
    Rcpp::traits::input_parameter< const double >::type wavelet_filter_penalty(wavelet_filter_penaltySEXP);
    Rcpp::traits::input_parameter< const double >::type acf_min(acf_minSEXP);
    Rcpp::traits::input_parameter< double >::type th_min(th_minSEXP);
    Rcpp::traits::input_parameter< double >::type th_max(th_maxSEXP);
    Rcpp::traits::input_parameter< double >::type dBIC_min(dBIC_minSEXP);
    Rcpp::traits::input_parameter< double >::type seg_len_min(seg_len_minSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type cpt_max(cpt_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(hilandyn2_int_cpp(X, nb, nc, nt, nr, ts_ids, cell_weights, rmse_out, len_seg_out, slo_seg_out, bln_mat_out, zsc_mat_out, mag_mat_out, sgn_mat_out, est_mat_out, nout, ts_len_min, gap_len_max, sd_method, cng_dir, noise_zscore, wavelet_filters, wavelet_level, wavelet_filter_penalty, acf_min, th_min, th_max, dBIC_min, seg_len_min, cpt_max, verbose));
    return rcpp_result_gen;
END_RCPP
}
// hilandyn2_map_cpp
arma::mat hilandyn2_map_cpp(arma::vec& v, const arma::uvec& v_dim, const arma::uword& win_side, const arma::uword& nb, arma::uword& nc, const arma::uword& nt, const arma::uword& nr, const arma::uvec& ts_ids, const bool cell_weights, const bool rmse_out, const bool len_seg_out, const bool slo_seg_out, const bool bln_mat_out, const bool zsc_mat_out, const bool mag_mat_out, const bool sgn_mat_out, const bool est_mat_out, const arma::uword& nout, const arma::uword ts_len_min, const arma::uword gap_len_max, const std::string& sd_method, const arma::vec& cng_dir, const double noise_zscore, const std::vector<std::string>& wavelet_filters, const arma::sword wavelet_level, const double wavelet_filter_penalty, const double acf_min, double th_min, double th_max, double dBIC_min, double seg_len_min, const arma::uword cpt_max, const int num_threads, bool debug);
RcppExport SEXP _hilandyn2_hilandyn2_map_cpp(SEXP vSEXP, SEXP v_dimSEXP, SEXP win_sideSEXP, SEXP nbSEXP, SEXP ncSEXP, SEXP ntSEXP, SEXP nrSEXP, SEXP ts_idsSEXP, SEXP cell_weightsSEXP, SEXP rmse_outSEXP, SEXP len_seg_outSEXP, SEXP slo_seg_outSEXP, SEXP bln_mat_outSEXP, SEXP zsc_mat_outSEXP, SEXP mag_mat_outSEXP, SEXP sgn_mat_outSEXP, SEXP est_mat_outSEXP, SEXP noutSEXP, SEXP ts_len_minSEXP, SEXP gap_len_maxSEXP, SEXP sd_methodSEXP, SEXP cng_dirSEXP, SEXP noise_zscoreSEXP, SEXP wavelet_filtersSEXP, SEXP wavelet_levelSEXP, SEXP wavelet_filter_penaltySEXP, SEXP acf_minSEXP, SEXP th_minSEXP, SEXP th_maxSEXP, SEXP dBIC_minSEXP, SEXP seg_len_minSEXP, SEXP cpt_maxSEXP, SEXP num_threadsSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type v_dim(v_dimSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type win_side(win_sideSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< arma::uword& >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type ts_ids(ts_idsSEXP);
    Rcpp::traits::input_parameter< const bool >::type cell_weights(cell_weightsSEXP);
    Rcpp::traits::input_parameter< const bool >::type rmse_out(rmse_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type len_seg_out(len_seg_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type slo_seg_out(slo_seg_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type bln_mat_out(bln_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type zsc_mat_out(zsc_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type mag_mat_out(mag_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type sgn_mat_out(sgn_mat_outSEXP);
    Rcpp::traits::input_parameter< const bool >::type est_mat_out(est_mat_outSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type nout(noutSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type ts_len_min(ts_len_minSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type gap_len_max(gap_len_maxSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type sd_method(sd_methodSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cng_dir(cng_dirSEXP);
    Rcpp::traits::input_parameter< const double >::type noise_zscore(noise_zscoreSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type wavelet_filters(wavelet_filtersSEXP);
    Rcpp::traits::input_parameter< const arma::sword >::type wavelet_level(wavelet_levelSEXP);
    Rcpp::traits::input_parameter< const double >::type wavelet_filter_penalty(wavelet_filter_penaltySEXP);
    Rcpp::traits::input_parameter< const double >::type acf_min(acf_minSEXP);
    Rcpp::traits::input_parameter< double >::type th_min(th_minSEXP);
    Rcpp::traits::input_parameter< double >::type th_max(th_maxSEXP);
    Rcpp::traits::input_parameter< double >::type dBIC_min(dBIC_minSEXP);
    Rcpp::traits::input_parameter< double >::type seg_len_min(seg_len_minSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type cpt_max(cpt_maxSEXP);
    Rcpp::traits::input_parameter< const int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(hilandyn2_map_cpp(v, v_dim, win_side, nb, nc, nt, nr, ts_ids, cell_weights, rmse_out, len_seg_out, slo_seg_out, bln_mat_out, zsc_mat_out, mag_mat_out, sgn_mat_out, est_mat_out, nout, ts_len_min, gap_len_max, sd_method, cng_dir, noise_zscore, wavelet_filters, wavelet_level, wavelet_filter_penalty, acf_min, th_min, th_max, dBIC_min, seg_len_min, cpt_max, num_threads, debug));
    return rcpp_result_gen;
END_RCPP
}
// mask_chunk_values_cpp
arma::vec mask_chunk_values_cpp(arma::vec& values, const arma::vec& mask_values, const arma::uword input_rows, const arma::uword input_columns);
RcppExport SEXP _hilandyn2_mask_chunk_values_cpp(SEXP valuesSEXP, SEXP mask_valuesSEXP, SEXP input_rowsSEXP, SEXP input_columnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mask_values(mask_valuesSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type input_rows(input_rowsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type input_columns(input_columnsSEXP);
    rcpp_result_gen = Rcpp::wrap(mask_chunk_values_cpp(values, mask_values, input_rows, input_columns));
    return rcpp_result_gen;
END_RCPP
}
// force_map_chunk_values_cpp
arma::vec force_map_chunk_values_cpp(arma::vec& values, const arma::vec& mask_values, const arma::uword input_rows, const arma::uword input_columns, const arma::uword time_steps, const arma::uvec& selected_band_positions, const arma::uvec& index_ids, const int sensor, const bool rescale_reflectance, const int num_threads);
RcppExport SEXP _hilandyn2_force_map_chunk_values_cpp(SEXP valuesSEXP, SEXP mask_valuesSEXP, SEXP input_rowsSEXP, SEXP input_columnsSEXP, SEXP time_stepsSEXP, SEXP selected_band_positionsSEXP, SEXP index_idsSEXP, SEXP sensorSEXP, SEXP rescale_reflectanceSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mask_values(mask_valuesSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type input_rows(input_rowsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type input_columns(input_columnsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type time_steps(time_stepsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type selected_band_positions(selected_band_positionsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type index_ids(index_idsSEXP);
    Rcpp::traits::input_parameter< const int >::type sensor(sensorSEXP);
    Rcpp::traits::input_parameter< const bool >::type rescale_reflectance(rescale_reflectanceSEXP);
    Rcpp::traits::input_parameter< const int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(force_map_chunk_values_cpp(values, mask_values, input_rows, input_columns, time_steps, selected_band_positions, index_ids, sensor, rescale_reflectance, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// force_composite_chunk_cpp
arma::mat force_composite_chunk_cpp(arma::vec& values, const arma::uword input_rows, const arma::uword input_columns, const arma::uword spectral_bands, const arma::uvec& acquisition_days, const arma::uvec& acquisition_doys, const arma::uvec& acquisition_years, const arma::uvec& acquisition_sensors, const arma::umat& intervals, const arma::uvec& target_days, const arma::uvec& target_doys, const arma::uword bins, const int method, const bool hybrid_binning, const bool use_weights, const double requested_distance, const double hybrid_max_days, const int num_threads, const unsigned int qai_mask);
RcppExport SEXP _hilandyn2_force_composite_chunk_cpp(SEXP valuesSEXP, SEXP input_rowsSEXP, SEXP input_columnsSEXP, SEXP spectral_bandsSEXP, SEXP acquisition_daysSEXP, SEXP acquisition_doysSEXP, SEXP acquisition_yearsSEXP, SEXP acquisition_sensorsSEXP, SEXP intervalsSEXP, SEXP target_daysSEXP, SEXP target_doysSEXP, SEXP binsSEXP, SEXP methodSEXP, SEXP hybrid_binningSEXP, SEXP use_weightsSEXP, SEXP requested_distanceSEXP, SEXP hybrid_max_daysSEXP, SEXP num_threadsSEXP, SEXP qai_maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type input_rows(input_rowsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type input_columns(input_columnsSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type spectral_bands(spectral_bandsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type acquisition_days(acquisition_daysSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type acquisition_doys(acquisition_doysSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type acquisition_years(acquisition_yearsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type acquisition_sensors(acquisition_sensorsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type intervals(intervalsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type target_days(target_daysSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type target_doys(target_doysSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type bins(binsSEXP);
    Rcpp::traits::input_parameter< const int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const bool >::type hybrid_binning(hybrid_binningSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_weights(use_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type requested_distance(requested_distanceSEXP);
    Rcpp::traits::input_parameter< const double >::type hybrid_max_days(hybrid_max_daysSEXP);
    Rcpp::traits::input_parameter< const int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type qai_mask(qai_maskSEXP);
    rcpp_result_gen = Rcpp::wrap(force_composite_chunk_cpp(values, input_rows, input_columns, spectral_bands, acquisition_days, acquisition_doys, acquisition_years, acquisition_sensors, intervals, target_days, target_doys, bins, method, hybrid_binning, use_weights, requested_distance, hybrid_max_days, num_threads, qai_mask));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hilandyn2_hilandyn2_int_cpp", (DL_FUNC) &_hilandyn2_hilandyn2_int_cpp, 31},
    {"_hilandyn2_hilandyn2_map_cpp", (DL_FUNC) &_hilandyn2_hilandyn2_map_cpp, 34},
    {"_hilandyn2_mask_chunk_values_cpp", (DL_FUNC) &_hilandyn2_mask_chunk_values_cpp, 4},
    {"_hilandyn2_force_map_chunk_values_cpp", (DL_FUNC) &_hilandyn2_force_map_chunk_values_cpp, 10},
    {"_hilandyn2_force_composite_chunk_cpp", (DL_FUNC) &_hilandyn2_force_composite_chunk_cpp, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_hilandyn2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
