# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hilandyn2_int_cpp <- function(X, nb, nc, nt, nr, ts_ids, cell_weights, rmse_out, len_seg_out, slo_seg_out, bln_mat_out, zsc_mat_out, mag_mat_out, sgn_mat_out, est_mat_out, nout, ts_len_min, gap_len_max, sd_method, cng_dir, noise_zscore, wavelet_filters, wavelet_level, wavelet_filter_penalty, acf_min, th_min, th_max, dBIC_min, seg_len_min, cpt_max, verbose) {
    .Call('_hilandyn2_hilandyn2_int_cpp', PACKAGE = 'hilandyn2', X, nb, nc, nt, nr, ts_ids, cell_weights, rmse_out, len_seg_out, slo_seg_out, bln_mat_out, zsc_mat_out, mag_mat_out, sgn_mat_out, est_mat_out, nout, ts_len_min, gap_len_max, sd_method, cng_dir, noise_zscore, wavelet_filters, wavelet_level, wavelet_filter_penalty, acf_min, th_min, th_max, dBIC_min, seg_len_min, cpt_max, verbose)
}

hilandyn2_map_cpp <- function(v, v_dim, win_side, nb, nc, nt, nr, ts_ids, cell_weights, rmse_out, len_seg_out, slo_seg_out, bln_mat_out, zsc_mat_out, mag_mat_out, sgn_mat_out, est_mat_out, nout, ts_len_min, gap_len_max, sd_method, cng_dir, noise_zscore, wavelet_filters, wavelet_level, wavelet_filter_penalty, acf_min, th_min, th_max, dBIC_min, seg_len_min, cpt_max, num_threads, debug) {
    .Call('_hilandyn2_hilandyn2_map_cpp', PACKAGE = 'hilandyn2', v, v_dim, win_side, nb, nc, nt, nr, ts_ids, cell_weights, rmse_out, len_seg_out, slo_seg_out, bln_mat_out, zsc_mat_out, mag_mat_out, sgn_mat_out, est_mat_out, nout, ts_len_min, gap_len_max, sd_method, cng_dir, noise_zscore, wavelet_filters, wavelet_level, wavelet_filter_penalty, acf_min, th_min, th_max, dBIC_min, seg_len_min, cpt_max, num_threads, debug)
}

mask_chunk_values_cpp <- function(values, mask_values, input_rows, input_columns) {
    .Call('_hilandyn2_mask_chunk_values_cpp', PACKAGE = 'hilandyn2', values, mask_values, input_rows, input_columns)
}

force_map_chunk_values_cpp <- function(values, mask_values, input_rows, input_columns, time_steps, selected_band_positions, index_ids, sensor, rescale_reflectance, num_threads) {
    .Call('_hilandyn2_force_map_chunk_values_cpp', PACKAGE = 'hilandyn2', values, mask_values, input_rows, input_columns, time_steps, selected_band_positions, index_ids, sensor, rescale_reflectance, num_threads)
}

force_composite_chunk_cpp <- function(values, input_rows, input_columns, spectral_bands, acquisition_days, acquisition_doys, acquisition_years, acquisition_sensors, intervals, target_days, target_doys, bins, method, hybrid_binning, use_weights, requested_distance, hybrid_max_days, num_threads, qai_mask = 799L) {
    .Call('_hilandyn2_force_composite_chunk_cpp', PACKAGE = 'hilandyn2', values, input_rows, input_columns, spectral_bands, acquisition_days, acquisition_doys, acquisition_years, acquisition_sensors, intervals, target_days, target_doys, bins, method, hybrid_binning, use_weights, requested_distance, hybrid_max_days, num_threads, qai_mask)
}

